In [111]:
import kagglehub
import pandas as pd
import numpy as np
import os
import minio
from minio import Minio
import boto3
from dotenv import load_dotenv

In [119]:
load_dotenv()
os.getenv("ACCESS_KEY_ID")
os.getenv("SECRET_ACCESS_KEY")
os.getenv("API_ENDPOINT")

'localhost:9000'

In [118]:
load_dotenv()
minio_client = boto3.client(
    "s3",
    aws_access_key_id=os.getenv("ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("SECRET_ACCESS_KEY"),
    endpoint_url= "http://" + os.getenv("API_ENDPOINT")
)

new_bucket = "landing-zone"
try:
    minio_client.create_bucket(Bucket=new_bucket)
except (minio_client.exceptions.BucketAlreadyExists, minio_client.exceptions.BucketAlreadyOwnedByYou):
    print(f"Bucket '{new_bucket}' already exists")

In [130]:
path = kagglehub.dataset_download("emmanuelfwerr/barcelona-car-accidents")
print(os.listdir(path))
print(os.listdir(path)[0])
file_path = os.path.join(path, os.listdir(path)[0])
filename = os.listdir(path)[0]
minio_client.upload_file(file_path, new_bucket, filename)
df = pd.read_csv(file_path)
print(df.head())

['accidents_opendata.csv']
accidents_opendata.csv
       case_id  district_id district_name neighborhood_id  \
0  2015S005807         -1.0    Desconegut            -1.0
1  2015S007685         10.0    Sant Martí            64.0
2  2015S001364         10.0    Sant Martí            64.0
3  2015S004325         10.0    Sant Martí            64.0
4  2015S005540         10.0    Sant Martí            64.0

            neighborhood_name  street_code          street_name postal_code  \
0                  Desconegut         -1.0           Desconegut  Desconegut
1  el Camp de l'Arpa del Clot     134801.0               Freser   0208 0208
2  el Camp de l'Arpa del Clot     161407.0            Indústria   0336 0336
3  el Camp de l'Arpa del Clot     226400.0  Las Navas de Tolosa   0343 0343
4  el Camp de l'Arpa del Clot      95506.0                Conca   0032 0034

  weekday_name weekday  ...                  cause_incident  n_deaths  \
0      Dimarts      Dm  ...        No és causa del  vianant       0.0
1      Dimarts      Dm  ...  Desobeir el senyal del semàfor       0.0
2     Dissabte      Ds  ...        No és causa del  vianant       0.0
3    Divendres      Dv  ...        No és causa del  vianant       0.0
4    Divendres      Dv  ...        No és causa del  vianant       0.0

   n_wounded_mild n_wounded_severe  n_victims  n_vehicles utm_coordinate_y  \
0             2.0              0.0        2.0         2.0               -1
1             1.0              0.0        1.0         1.0       4585420,58
2             1.0              0.0        1.0         1.0       4585555,86
3             1.0              0.0        1.0         2.0       4585565,44
4             2.0              0.0        2.0         1.0       4585260,16

  utm_coordinate_x  longitude  latitude
0               -1        NaN       NaN
1        431779,16        NaN       NaN
2        431913,65        NaN       NaN
3        431946,45        NaN       NaN
4        431530,84        NaN       NaN

[5 rows x 27 columns]

/var/folders/x6/h1hq1rf10hn6lybhqt5n942w0000gn/T/ipykernel_24835/2171732771.py:7: DtypeWarning: Columns (0: neighborhood_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [131]:
path = kagglehub.dataset_download("jessicarippman/barcelona-car-accidents-dataset")
print(path)
print(os.listdir(path))
vec_elem = os.listdir(path)
datasets = []
for index, dataset in enumerate(vec_elem):
    file_path = os.path.join(path, os.listdir(path)[index])
    datasets.append(pd.read_csv(file_path))
    minio_client.upload_file(file_path, new_bucket, os.listdir(path)[index])

/Users/carlesaguilera/.cache/kagglehub/datasets/jessicarippman/barcelona-car-accidents-dataset/versions/1
['accidents_by_date.csv', 'barcelona_accidents.csv']

In [132]:
path = kagglehub.dataset_download("falloufall21/barcelona-car-accident-2023")
print(path)
print(os.listdir(path))
path_file = os.path.join(path, os.listdir(path)[0])
minio_client.upload_file(path_file, new_bucket, os.listdir(path)[0])
df2 = pd.read_csv(path_file)
df2

/Users/carlesaguilera/.cache/kagglehub/datasets/falloufall21/barcelona-car-accident-2023/versions/1
['2023_accidents_causa_conductor_gu_bcn_.csv']

,Numero_expedient,Codi_districte,Nom_districte,Codi_barri,Nom_barri,Codi_carrer,Nom_carrer,Num_postal,Descripcio_dia_setmana,NK_Any,Mes_any,Nom_mes,Dia_mes,Hora_dia,Descripcio_torn,Descripcio_causa_mediata,Coordenada_UTM_X_ED50,Coordenada_UTM_Y_ED50,Longitud_WGS84,Latitud_WGS84
0,2023S000699,-1,Desconegut,-1,Desconegut,-1,Rovira (ascendent) ...,0,Dissabte,2023,2,Febrer,4,16,Tarda,Manca d'atenció a la conducció,430443.36,4585232.00,2.166596,41.413783
1,2023S005197,-1,Desconegut,-1,Desconegut,-1,Estatut de Catalunya ...,11,Divendres,2023,9,Setembre,1,13,Matí,No respectar distàncies,429493.73,4587108.15,2.155015,41.430598
2,2023S007430,-1,Desconegut,-1,Desconegut,-1,Rovira (ascendent) ...,0,Divendres,2023,12,Desembre,15,11,Matí,No respectar distàncies,430443.36,4585232.00,2.166596,41.413783
3,2023S000961,-1,Desconegut,-1,Desconegut,-1,Amílcar ...,120,Dissabte,2023,1,Gener,28,14,Tarda,No respectat pas de vianants,430955.45,4586335.10,2.172596,41.423762
4,2023S006486,-1,Desconegut,-1,Desconegut,-1,Augusta / Hort de la Vila ...,NaN,Dijous,2023,11,Novembre,2,14,Tarda,Desobeir semàfor,426883.33,4583690.92,2.124189,41.399587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8892,2023S000678,8,Nou Barris,44,Vilapicina i la Torre Llobeta,119003,Fabra i Puig,0181 0181,Divendres,2023,2,Febrer,3,17,Tarda,Avançament defectuós/improcedent,431379.36,4587039.88,2.177589,41.430147
8893,2023S006888,8,Nou Barris,44,Vilapicina i la Torre Llobeta,45701,Quinze,0068 0068,Dilluns,2023,11,Novembre,20,14,Tarda,No respectar distàncies,431122.09,4586910.29,2.174525,41.428957
8894,2023S007283,8,Nou Barris,45,Porta,256401,Pintor Alsamora,0001 0001,Divendres,2023,12,Desembre,8,6,Matí,Altres,431890.58,4587477.65,2.183657,41.434133
8895,2023S007283,8,Nou Barris,45,Porta,256401,Pintor Alsamora,0001 0001,Divendres,2023,12,Desembre,8,6,Matí,Manca d'atenció a la conducció,431890.58,4587477.65,2.183657,41.434133
8896,2023S004812,8,Nou Barris,44,Vilapicina i la Torre Llobeta,274505,Ramon Albó,0059 0061,Dimecres,2023,8,Agost,9,12,Matí,Manca d'atenció a la conducció,431359.22,4586651.00,2.177392,41.426642

**SEMI-STRUCTURED DATA**

In [138]:
import requests

url = "https://opendata-ajuntament.barcelona.cat/data/dataset/425f3411-963d-4ccc-a8de-c9422d923378/resource/2f308e87-8bb1-4145-97f2-3dcce62623b9/download"

response = requests.get(url)
print(response.text)
key = f"elem1.txt"
minio_client.put_object(
    Bucket=new_bucket,
    Key= key,
    Body = response.text.encode("utf-8"),
    ContentType="text/plain; charset=utf-8"
)

La Rambla sentit descendent: tallada al trànsit per obres.             Carrer del Comte d´Urgell, sentit muntanya, a l´altura Carrer de Rosselló, tallada per obres.             C. Balmes de General Mitre a Pl. Molina, restriccions al trànsit per obres.             C. Muntaner a l´altura de C. la Forja tallat al trànsit per obres.             C. Llull a l´ altura de Bac de Roda, restriccions al trànsit per tasques de manteniment.             Rda. de Dalt sentit Llobregat a l´altura del T. Palamos retencions de trànsit per vehicle avariat.             Túnel de la Rovira sentit mar tallat per obres.             Josep Pla a l´altura de Pallars, restriccions al trànsit per tasques de manteniment.
La Rambla sentit descendent: tallada al trànsit per obres.             Carrer del Comte d´Urgell, sentit muntanya, a l´altura Carrer de Rosselló, tallada per obres.             C. Balmes de General Mitre a Pl. Molina, restriccions al trànsit per obres.             C. Muntaner a l´altura de C. la Forja tallat al trànsit per obres.             C. Llull a l´ altura de Bac de Roda, restriccions al trànsit per tasques de manteniment.             Rda. de Dalt sentit Llobregat a l´altura del T. Palamos retencions de trànsit per vehicle avariat.             Túnel de la Rovira sentit mar tallat per obres.             Josep Pla a l´altura de Pallars, restriccions al trànsit per tasques de manteniment.
La Rambla sentit descendent: tallada al trànsit per obres.             Carrer del Comte d´Urgell, sentit muntanya, a l´altura Carrer de Rosselló, tallada per obres.             C. Balmes de General Mitre a Pl. Molina, restriccions al trànsit per obres.             C. Muntaner a l´altura de C. la Forja tallat al trànsit per obres.             C. Llull a l´ altura de Bac de Roda, restriccions al trànsit per tasques de manteniment.             Rda. de Dalt sentit Llobregat a l´altura del T. Palamos retencions de trànsit per vehicle avariat.             Túnel de la Rovira sentit mar tallat per obres.             Josep Pla a l´altura de Pallars, restriccions al trànsit per tasques de manteniment.

{'ResponseMetadata': {'RequestId': '18965590DB11899B',
  'HostId': 'dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'accept-ranges': 'bytes',
   'content-length': '0',
   'etag': '"853a8efcb12672b11d4e3746c392d0ec"',
   'server': 'MinIO',
   'strict-transport-security': 'max-age=31536000; includeSubDomains',
   'vary': 'Origin, Accept-Encoding',
   'x-amz-checksum-crc32': 'DVzBXw==',
   'x-amz-checksum-type': 'FULL_OBJECT',
   'x-amz-id-2': 'dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8',
   'x-amz-request-id': '18965590DB11899B',
   'x-content-type-options': 'nosniff',
   'x-ratelimit-limit': '1023',
   'x-ratelimit-remaining': '1023',
   'x-xss-protection': '1; mode=block',
   'date': 'Sat, 21 Feb 2026 18:13:04 GMT'},
  'RetryAttempts': 0},
 'ETag': '"853a8efcb12672b11d4e3746c392d0ec"',
 'ChecksumCRC32': 'DVzBXw==',
 'ChecksumType': 'FULL_OBJECT'}

In [ ]:
import feedparser
import pandas as pd
rss_url = "http://www.gencat.cat/transit/opendata/incidenciesRSS.xml"
feed = feedparser.parse(rss_url)

rows = []

for e in feed.entries:
    rows.append({
        "title": e.get("title"),
        "link": e.get("link"),
        "published": e.get("published"),
        "summary": e.get("summary"),
    })
    
df["published"] = pd.to_datetime(df["published"], errors = "coerce")
today  = pd.Timestamp.today().normalize()
df_today = df[df["published"].dt.normalize() == today]

value = df_today.iloc[0]['summary']
#value.str.strip(" | ", expand = True)

df_elem = df["summary"].str.split("|", expand = True)
df_elem
f_elem = df_elem[
    (df_elem[2].str.upper() == "BARCELONA")
].copy()

f_elem
# NO HI HA CAP, PERÒ SI HI HAGUES ALGO D'ACTUALITAT A BARCELONA, DONCS ES VEURIA.

Empty DataFrame
Columns: [0, 1, 2, 3, 4]
Index: []

In [ ]:
import pandas as pd
import time
import requests
from datetime import datetime
from urllib.parse import urlparse, urlunparse

urls = [
    "https://www.bcn.cat/transit/imatges/DiagonalMCristina.gif",
    "https://www.bcn.cat/transit/imatges/RondadeDaltCrtaEsplugues.gif",
    "https://mct.gencat.cat/mct2bo/TransitCamera?nom=sc29.gif&visualitzacio=imatge",
    "https://www.bcn.cat/transit/imatges/RondadeDaltSantGervasi.gif",
    "https://www.bcn.cat/transit/imatges/BalmesMitre.gif",
    "https://www.bcn.cat/transit/imatges/PlMolina.gif",
    "https://www.bcn.cat/transit/imatges/GranViaMarina.gif",
    "https://www.bcn.cat/transit/imatges/GranViaMarina.gif",
    "https://www.bcn.cat/transit/imatges/RondaLitoralBonPastor.gif",
    "https://www.bcn.cat/transit/imatges/RondaLitoralBadajoz.gif",
    "https://www.bcn.cat/transit/imatges/PlAntonioLopez.gif",
    "https://www.bcn.cat/transit/imatges/RondaLitoralMollFusta.gif",
    "https://www.bcn.cat/transit/imatges/RondaLitoralZonaFranca.gif",
    "https://www.bcn.cat/transit/imatges/PlCerda.gif",
    "https://www.bcn.cat/transit/imatges/PlEspanya.gif",
    "https://mct.gencat.cat/mct2bo/TransitCamera?nom=nc87.gif&visualitzacio=imatge",
    "https://mct.gencat.cat/mct2bo/TransitCamera?nom=nc86.gif&visualitzacio=imatge",
]

rows = []
for u in urls:
    if "mct.gencat.cat" in u:
        p = urlparse(u)
        u = urlunparse(p._replace(scheme="http"))

        # params NO calen aquí
        params = None
    else:
        # cache-buster només per bcn.cat
        params = {"a": 1, "time": int(time.time() * 1000)}

    r = requests.get(u, params=params, timeout=30)
    r.raise_for_status()

    camera = urlparse(u).path.split("/")[-1]  # nom del fitxer o 'TransitCamera'
    rows.append({
        "camera": camera,
        "timestamp": datetime.now(),
        "image_bytes": r.content,
        "content_type": r.headers.get("Content-Type"),
        "url": u
    })

df_img = pd.DataFrame(rows)
df_img

,camera,timestamp,image_bytes,content_type,url
0,DiagonalMCristina.gif,2026-02-21 16:58:22.202363,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x13\x0e\x13\...,image/gif,https://www.bcn.cat/transit/imatges/DiagonalMC...
1,RondadeDaltCrtaEsplugues.gif,2026-02-21 16:58:22.457773,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x11\x13\x17\...,image/gif,https://www.bcn.cat/transit/imatges/RondadeDal...
2,TransitCamera,2026-02-21 16:58:22.617939,b'GIF89a\xc0\x02\xe0\x01\xf7\x00\x00\x00#\x00\...,image/jpeg,http://mct.gencat.cat/mct2bo/TransitCamera?nom...
3,RondadeDaltSantGervasi.gif,2026-02-21 16:58:22.922263,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x05\x04\x04\...,image/gif,https://www.bcn.cat/transit/imatges/RondadeDal...
4,BalmesMitre.gif,2026-02-21 16:58:23.159323,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x15\x15\x1d\...,image/gif,https://www.bcn.cat/transit/imatges/BalmesMitr...
5,PlMolina.gif,2026-02-21 16:58:23.375904,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x19\x17\x18\...,image/gif,https://www.bcn.cat/transit/imatges/PlMolina.gif
6,GranViaMarina.gif,2026-02-21 16:58:23.582137,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x17\x18\x1b\...,image/gif,https://www.bcn.cat/transit/imatges/GranViaMar...
7,GranViaMarina.gif,2026-02-21 16:58:23.807656,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x17\x18\x1b\...,image/gif,https://www.bcn.cat/transit/imatges/GranViaMar...
8,RondaLitoralBonPastor.gif,2026-02-21 16:58:24.033706,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x03\x03\x03\...,image/gif,https://www.bcn.cat/transit/imatges/RondaLitor...
9,RondaLitoralBadajoz.gif,2026-02-21 16:58:24.229155,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x10\x12\x16\...,image/gif,https://www.bcn.cat/transit/imatges/RondaLitor...
10,PlAntonioLopez.gif,2026-02-21 16:58:24.424180,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x17\x16\x18\...,image/gif,https://www.bcn.cat/transit/imatges/PlAntonioL...
11,RondaLitoralMollFusta.gif,2026-02-21 16:58:24.608051,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x13\x13\x1b\...,image/gif,https://www.bcn.cat/transit/imatges/RondaLitor...
12,RondaLitoralZonaFranca.gif,2026-02-21 16:58:24.792488,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x04\x05\x04\...,image/gif,https://www.bcn.cat/transit/imatges/RondaLitor...
13,PlCerda.gif,2026-02-21 16:58:25.022786,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x13\x16\x1b\...,image/gif,https://www.bcn.cat/transit/imatges/PlCerda.gif
14,PlEspanya.gif,2026-02-21 16:58:25.239702,b'GIF89a@\x01\xf0\x00\xf7\x00\x00\x16\x15\x19\...,image/gif,https://www.bcn.cat/transit/imatges/PlEspanya.gif
15,TransitCamera,2026-02-21 16:58:25.361286,b'GIF89a\xc0\x02\xe0\x01\xf7\x00\x00lK\x00k^\x...,image/jpeg,http://mct.gencat.cat/mct2bo/TransitCamera?nom...
16,TransitCamera,2026-02-21 16:58:25.492887,b'GIF89a\xc0\x02\xe0\x01\xf7\x00\x00$$\x00$$\x...,image/jpeg,http://mct.gencat.cat/mct2bo/TransitCamera?nom...

In [ ]:
import requests
import pandas as pd

BEARER = "TU_BARER_TOKEN"

def x_get(url, params=None):
    headers = {"Authorization": f"Bearer {BEARER}"}
    r = requests.get(url, headers=headers, params=params, timeout=30)
    r.raise_for_status()
    return r.json()


username = "transit"
user = x_get(f"https://api.x.com/2/users/by/username/{username}")
user_id = user["data"]["id"]

# 2) Últims 20 tweets/posts
tl = x_get(
    f"https://api.x.com/2/users/{user_id}/tweets",
    params={
        "max_results": 1,
        "tweet.fields": "created_at,lang",
        # "exclude": "replies,retweets"  # descomenta si vols només posts originals
    },
)

df = pd.DataFrame(tl.get("data", []))

# 3) Filtre Barcelona (ajusta paraules clau segons necessitis)
pattern = r"(?:\bBarcelona\b|Nus Trinitat|Ronda(?:\s+Litoral|\s+de\s+Dalt)|B-10|B-20)"
df_bcn = df[df["text"].str.contains(pattern, case=False, na=False, regex=True)].copy()

df_bcn[["created_at", "text"]]

HTTPError: 402 Client Error: Payment Required for url: https://api.x.com/2/users/by/username/transit